baseURL = "https://www.glads.fr"
title = "GLADS | Architecture · Développement · Sécurité"
theme = "air"
defaultContentLanguage = "fr"

enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS", "section"]

[languages]
  [languages.fr]
    languageCode = "fr-FR"
    contentDir = "content/fr"
    languageName = "Français"
    weight = 1

  [[languages.fr.menus.main]]
    name = "Accueil"
    pageRef = "/"
    weight = 10

  [[languages.fr.menus.footer]]
    name = "GLADS"
    pageRef = "/"
    weight = 10

[params]
  mainColor = "#0f2b46"
  footer = "GLADS - Guillaume Laurent Architecture Développement Sécurité - EURL au capital de 1 000 euros"
  [params.author]
    name = "Guillaume Laurent"
    siteUrl = "https://www.glads.fr/"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true
